---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by hackermanmajo.
--- DateTime: 02.11.25 11:41
---

AppSettingsMenu = {}
AppSettingsMenu.__index = AppSettingsMenu

function AppSettingsMenu.new()
    local self = setmetatable({}, AppSettingsMenu)
    -- simple example settings
    self.options = {
        { name = "Master Volume", value = 100 },
        { name = "Fullscreen", value = false },
        { name = "VSync", value = true },
    }
    self.selection = 1
    return self
end

function AppSettingsMenu:update(dt)
    T.number(dt)
    -- placeholder: input handling can be added here later
end

function AppSettingsMenu:render()
    love.graphics.clear(0.05, 0.05, 0.06)
    love.graphics.setColor(1, 1, 1)
    love.graphics.printf("App Settings", 0, love.graphics.getHeight() / 2 - 80, love.graphics.getWidth(), "center")

    for i, opt in ipairs(self.options) do
        local y = love.graphics.getHeight() / 2 - 80 + 24 * i
        local txt = opt.name .. ": " .. tostring(opt.value)
        if i == self.selection then
            -- emphasize selected option
            love.graphics.setColor(0.9, 0.9, 0.2)
        else
            love.graphics.setColor(1, 1, 1)
        end
        love.graphics.printf(txt, 0, y, love.graphics.getWidth(), "center")
    end
end
