---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by hackermanmajo.
--- DateTime: 02.11.25 11:41
---

LoadCampMenu = {}
LoadCampMenu.__index = LoadCampMenu

function LoadCampMenu.new()
    local self = setmetatable({}, LoadCampMenu)
    self.selection = 1
    return self
end

function LoadCampMenu:update(dt)
    T.number(dt)
end

function LoadCampMenu:render()
    love.graphics.clear(0.12, 0.12, 0.12)
    love.graphics.setColor(1,1,1)
    love.graphics.printf("Load Campaign Menu", 0, love.graphics.getHeight() / 2 - 20, love.graphics.getWidth(), "center")
end
