---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by hackermanmajo.
--- DateTime: 02.11.25 11:30
---

LoadScenarioMenu = {}
LoadScenarioMenu.__index = LoadScenarioMenu

function LoadScenarioMenu.new()
    local self = setmetatable({}, LoadScenarioMenu)
    self.selection = 1
    return self
end

function LoadScenarioMenu:update(dt)
    T.number(dt)
end

function LoadScenarioMenu:render()
    love.graphics.clear(0.12, 0.12, 0.12)
    love.graphics.setColor(1,1,1)
    love.graphics.printf("Load Scenario Menu", 0, love.graphics.getHeight() / 2 - 20, love.graphics.getWidth(), "center")
end
