---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by hackermanmajo.
--- DateTime: 02.11.25 10:52
---

StartBattleMenu = {}
StartBattleMenu.__index = StartBattleMenu

function StartBattleMenu.new()
    local self = setmetatable({}, StartBattleMenu)
    return self
end

function StartBattleMenu:update(dt)
    T.number(dt)
end

function StartBattleMenu:render()
    love.graphics.clear(0.08, 0.08, 0.08)
    love.graphics.setColor(1,1,1)
    love.graphics.printf("Start Battle Menu", 0, love.graphics.getHeight() / 2 - 20, love.graphics.getWidth(), "center")
end
